### ISSUE TITLE
You can organize Readme.md description better

### ISSUE THREAD

**Issue by rudnitskih** [Ultimo2905/DZ-6.10.2018#1]
It is not required, but you can improve your description file. Check this example https://github.com/ArtemChubatyi/css_selectors/blob/master/README.md and try to improve your `md` file.

**Comment by Ultimo2905** [comment]
Так я так хотів, але згадав, що Ти сам казав, що змінювати HTML код не можна і все треба робити в HTML коді, а не в окремому файлі css.

**Comment by Ultimo2905** [comment]
Хоча ваш запропонований варіант краще і я так намагався ще на парі робити.
